#!/bin/sh
#2559 PERF: DOWN UP last
# Load Plugin Functions

function getConfigValue {
	if [ ! -f $BARTLBY_CONFIG ];
	then
		echo "Config $BARTLBY_CONFIG doesnt look like a file"  3
		exit;
	fi;
	
	r=`cat $BARTLBY_CONFIG |grep $1|awk -F"=" '{print \$2}'`
	echo $r;

}


RRD_HTDOCS=$(getConfigValue performance_rrd_htdocs|tr -d [:blank:]);

RRD_TOOLCFG=$(getConfigValue rrd_tool|tr -d [:blank:]);
RRDTOOL=${RRD_TOOLCFG:-'/usr/bin/rrdtool'}

RRDFILE="${RRD_HTDOCS}/${1}_bartlby_if.rrd";

PNGFILE="${RRD_HTDOCS}/${1}_bartlby_if.png";
PNGFILE_SEVEN="${RRD_HTDOCS}/${1}_bartlby_if7.png";


#Check if RRD file is existing

if [ ! -f $RRDFILE ];
then
	if [ "x${BARTLBY_HOME}" != "x" ];
	then
		ORIGFILE="${BARTLBY_HOME}/perf/defaults/bartlby_if.rrd";
		if [ -f $ORIGFILE ];
		then
			cp $ORIGFILE $RRDFILE;
			chmod a+rw $RRDFILE;
		fi;
	else
		echo "BARTLBY_HOME not set maybe you are running from command line";
		exit;
	fi;
fi;





if [ "$1" = "graph" ];
then
	RRDFILE="${RRD_HTDOCS}/${2}_bartlby_if.rrd";

	PNGFILE="${RRD_HTDOCS}/${2}_bartlby_if.png";
	PNGFILE_SEVEN="${RRD_HTDOCS}/${2}_bartlby_if7.png";

$RRDTOOL graph $PNGFILE -a PNG -h 300 -w 600 -s -86400 -v "Data Throughput" \
    DEF:in=${RRDFILE}:in:AVERAGE \
    DEF:out=${RRDFILE}:out:AVERAGE \
    'CDEF:kbin=in,1024,/' \
    'CDEF:kbout=out,1024,/' \
    'AREA:in#00FF00:Bandwidth In'                               'LINE1:out#0000FF:Bandwidth Out\j' \
    'GPRINT:kbin:LAST:Last Bandwidth In\:    %3.2lf KBps'       'GPRINT:kbout:LAST:Last Bandwidth Out\:   %3.2lf KBps\j' \
    'GPRINT:kbin:AVERAGE:Average Bandwidth In\: %3.2lf KBps'    'GPRINT:kbout:AVERAGE:Average Bandwidth Out\:%3.2lf KBps\j' > /dev/null

	echo "generated 24 hour graph";
$RRDTOOL graph $PNGFILE_SEVEN -a PNG -h 300 -w 600 -s -604800 -v "Data Throughput" \
    DEF:in=${RRDFILE}:in:AVERAGE \
    DEF:out=${RRDFILE}:out:AVERAGE \
    'CDEF:kbin=in,1024,/' \
    'CDEF:kbout=out,1024,/' \
    'AREA:in#00FF00:Bandwidth In'                               'LINE1:out#0000FF:Bandwidth Out\j' \
    'GPRINT:kbin:LAST:Last Bandwidth In\:    %3.2lf KBps'       'GPRINT:kbout:LAST:Last Bandwidth Out\:   %3.2lf KBps\j' \
    'GPRINT:kbin:AVERAGE:Average Bandwidth In\: %3.2lf KBps'    'GPRINT:kbout:AVERAGE:Average Bandwidth Out\:%3.2lf KBps\j' > /dev/null

	echo "generated 7 day graph";
else
	D=$3
	U=$4
	$RRDTOOL update $RRDFILE N:$D:$U
fi;


